/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGCSHARP


#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif 
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



#include <stdlib.h>
#include <string.h>
#include <stdio.h>


/* Support for throwing C# exceptions from C/C++. There are two types: 
 * Exceptions that take a message and ArgumentExceptions that take a message and a parameter name. */
typedef enum {
  SWIG_CSharpApplicationException,
  SWIG_CSharpArithmeticException,
  SWIG_CSharpDivideByZeroException,
  SWIG_CSharpIndexOutOfRangeException,
  SWIG_CSharpInvalidCastException,
  SWIG_CSharpInvalidOperationException,
  SWIG_CSharpIOException,
  SWIG_CSharpNullReferenceException,
  SWIG_CSharpOutOfMemoryException,
  SWIG_CSharpOverflowException,
  SWIG_CSharpSystemException
} SWIG_CSharpExceptionCodes;

typedef enum {
  SWIG_CSharpArgumentException,
  SWIG_CSharpArgumentNullException,
  SWIG_CSharpArgumentOutOfRangeException
} SWIG_CSharpExceptionArgumentCodes;

typedef void (SWIGSTDCALL* SWIG_CSharpExceptionCallback_t)(const char *);
typedef void (SWIGSTDCALL* SWIG_CSharpExceptionArgumentCallback_t)(const char *, const char *);

typedef struct {
  SWIG_CSharpExceptionCodes code;
  SWIG_CSharpExceptionCallback_t callback;
} SWIG_CSharpException_t;

typedef struct {
  SWIG_CSharpExceptionArgumentCodes code;
  SWIG_CSharpExceptionArgumentCallback_t callback;
} SWIG_CSharpExceptionArgument_t;

static SWIG_CSharpException_t SWIG_csharp_exceptions[] = {
  { SWIG_CSharpApplicationException, NULL },
  { SWIG_CSharpArithmeticException, NULL },
  { SWIG_CSharpDivideByZeroException, NULL },
  { SWIG_CSharpIndexOutOfRangeException, NULL },
  { SWIG_CSharpInvalidCastException, NULL },
  { SWIG_CSharpInvalidOperationException, NULL },
  { SWIG_CSharpIOException, NULL },
  { SWIG_CSharpNullReferenceException, NULL },
  { SWIG_CSharpOutOfMemoryException, NULL },
  { SWIG_CSharpOverflowException, NULL },
  { SWIG_CSharpSystemException, NULL }
};

static SWIG_CSharpExceptionArgument_t SWIG_csharp_exceptions_argument[] = {
  { SWIG_CSharpArgumentException, NULL },
  { SWIG_CSharpArgumentNullException, NULL },
  { SWIG_CSharpArgumentOutOfRangeException, NULL }
};

static void SWIGUNUSED SWIG_CSharpSetPendingException(SWIG_CSharpExceptionCodes code, const char *msg) {
  SWIG_CSharpExceptionCallback_t callback = SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions)/sizeof(SWIG_CSharpException_t)) {
    callback = SWIG_csharp_exceptions[code].callback;
  }
  callback(msg);
}

static void SWIGUNUSED SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpExceptionArgumentCodes code, const char *msg, const char *param_name) {
  SWIG_CSharpExceptionArgumentCallback_t callback = SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions_argument)/sizeof(SWIG_CSharpExceptionArgument_t)) {
    callback = SWIG_csharp_exceptions_argument[code].callback;
  }
  callback(msg, param_name);
}


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionCallbacks_EffekseerNative(
                                                SWIG_CSharpExceptionCallback_t applicationCallback,
                                                SWIG_CSharpExceptionCallback_t arithmeticCallback,
                                                SWIG_CSharpExceptionCallback_t divideByZeroCallback, 
                                                SWIG_CSharpExceptionCallback_t indexOutOfRangeCallback, 
                                                SWIG_CSharpExceptionCallback_t invalidCastCallback,
                                                SWIG_CSharpExceptionCallback_t invalidOperationCallback,
                                                SWIG_CSharpExceptionCallback_t ioCallback,
                                                SWIG_CSharpExceptionCallback_t nullReferenceCallback,
                                                SWIG_CSharpExceptionCallback_t outOfMemoryCallback, 
                                                SWIG_CSharpExceptionCallback_t overflowCallback, 
                                                SWIG_CSharpExceptionCallback_t systemCallback) {
  SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback = applicationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpArithmeticException].callback = arithmeticCallback;
  SWIG_csharp_exceptions[SWIG_CSharpDivideByZeroException].callback = divideByZeroCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIndexOutOfRangeException].callback = indexOutOfRangeCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidCastException].callback = invalidCastCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidOperationException].callback = invalidOperationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIOException].callback = ioCallback;
  SWIG_csharp_exceptions[SWIG_CSharpNullReferenceException].callback = nullReferenceCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOutOfMemoryException].callback = outOfMemoryCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOverflowException].callback = overflowCallback;
  SWIG_csharp_exceptions[SWIG_CSharpSystemException].callback = systemCallback;
}

#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionArgumentCallbacks_EffekseerNative(
                                                SWIG_CSharpExceptionArgumentCallback_t argumentCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentNullCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentOutOfRangeCallback) {
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback = argumentCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentNullException].callback = argumentNullCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentOutOfRangeException].callback = argumentOutOfRangeCallback;
}


/* Callback for returning strings to C# without leaking memory */
typedef char * (SWIGSTDCALL* SWIG_CSharpStringHelperCallback)(const char *);
static SWIG_CSharpStringHelperCallback SWIG_csharp_string_callback = NULL;


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterStringCallback_EffekseerNative(SWIG_CSharpStringHelperCallback callback) {
  SWIG_csharp_string_callback = callback;
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, msg, ""); return nullreturn; } else


/* Callback for returning strings to C# without leaking memory */
typedef void * (SWIGSTDCALL* SWIG_CSharpWStringHelperCallback)(const wchar_t *);
static SWIG_CSharpWStringHelperCallback SWIG_csharp_wstring_callback = NULL;


#ifdef __cplusplus
extern "C"
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterWStringCallback_EffekseerNative(SWIG_CSharpWStringHelperCallback callback) {
  SWIG_csharp_wstring_callback = callback;
}


#include "dll.h"


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void SWIGSTDCALL CSharp_ViewerParamater_GuideWidth_set(void * jarg1, int jarg2) {
  ViewerParamater *arg1 = (ViewerParamater *) 0 ;
  int32_t arg2 ;
  
  arg1 = (ViewerParamater *)jarg1; 
  arg2 = (int32_t)jarg2; 
  if (arg1) (arg1)->GuideWidth = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_ViewerParamater_GuideWidth_get(void * jarg1) {
  int jresult ;
  ViewerParamater *arg1 = (ViewerParamater *) 0 ;
  int32_t result;
  
  arg1 = (ViewerParamater *)jarg1; 
  result = (int32_t) ((arg1)->GuideWidth);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_ViewerParamater_GuideHeight_set(void * jarg1, int jarg2) {
  ViewerParamater *arg1 = (ViewerParamater *) 0 ;
  int32_t arg2 ;
  
  arg1 = (ViewerParamater *)jarg1; 
  arg2 = (int32_t)jarg2; 
  if (arg1) (arg1)->GuideHeight = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_ViewerParamater_GuideHeight_get(void * jarg1) {
  int jresult ;
  ViewerParamater *arg1 = (ViewerParamater *) 0 ;
  int32_t result;
  
  arg1 = (ViewerParamater *)jarg1; 
  result = (int32_t) ((arg1)->GuideHeight);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_ViewerParamater_RateOfMagnification_set(void * jarg1, float jarg2) {
  ViewerParamater *arg1 = (ViewerParamater *) 0 ;
  float arg2 ;
  
  arg1 = (ViewerParamater *)jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->RateOfMagnification = arg2;
}


SWIGEXPORT float SWIGSTDCALL CSharp_ViewerParamater_RateOfMagnification_get(void * jarg1) {
  float jresult ;
  ViewerParamater *arg1 = (ViewerParamater *) 0 ;
  float result;
  
  arg1 = (ViewerParamater *)jarg1; 
  result = (float) ((arg1)->RateOfMagnification);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_ViewerParamater_IsPerspective_set(void * jarg1, unsigned int jarg2) {
  ViewerParamater *arg1 = (ViewerParamater *) 0 ;
  bool arg2 ;
  
  arg1 = (ViewerParamater *)jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->IsPerspective = arg2;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_ViewerParamater_IsPerspective_get(void * jarg1) {
  unsigned int jresult ;
  ViewerParamater *arg1 = (ViewerParamater *) 0 ;
  bool result;
  
  arg1 = (ViewerParamater *)jarg1; 
  result = (bool) ((arg1)->IsPerspective);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_ViewerParamater_IsOrthographic_set(void * jarg1, unsigned int jarg2) {
  ViewerParamater *arg1 = (ViewerParamater *) 0 ;
  bool arg2 ;
  
  arg1 = (ViewerParamater *)jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->IsOrthographic = arg2;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_ViewerParamater_IsOrthographic_get(void * jarg1) {
  unsigned int jresult ;
  ViewerParamater *arg1 = (ViewerParamater *) 0 ;
  bool result;
  
  arg1 = (ViewerParamater *)jarg1; 
  result = (bool) ((arg1)->IsOrthographic);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_ViewerParamater_FocusX_set(void * jarg1, float jarg2) {
  ViewerParamater *arg1 = (ViewerParamater *) 0 ;
  float arg2 ;
  
  arg1 = (ViewerParamater *)jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->FocusX = arg2;
}


SWIGEXPORT float SWIGSTDCALL CSharp_ViewerParamater_FocusX_get(void * jarg1) {
  float jresult ;
  ViewerParamater *arg1 = (ViewerParamater *) 0 ;
  float result;
  
  arg1 = (ViewerParamater *)jarg1; 
  result = (float) ((arg1)->FocusX);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_ViewerParamater_FocusY_set(void * jarg1, float jarg2) {
  ViewerParamater *arg1 = (ViewerParamater *) 0 ;
  float arg2 ;
  
  arg1 = (ViewerParamater *)jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->FocusY = arg2;
}


SWIGEXPORT float SWIGSTDCALL CSharp_ViewerParamater_FocusY_get(void * jarg1) {
  float jresult ;
  ViewerParamater *arg1 = (ViewerParamater *) 0 ;
  float result;
  
  arg1 = (ViewerParamater *)jarg1; 
  result = (float) ((arg1)->FocusY);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_ViewerParamater_FocusZ_set(void * jarg1, float jarg2) {
  ViewerParamater *arg1 = (ViewerParamater *) 0 ;
  float arg2 ;
  
  arg1 = (ViewerParamater *)jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->FocusZ = arg2;
}


SWIGEXPORT float SWIGSTDCALL CSharp_ViewerParamater_FocusZ_get(void * jarg1) {
  float jresult ;
  ViewerParamater *arg1 = (ViewerParamater *) 0 ;
  float result;
  
  arg1 = (ViewerParamater *)jarg1; 
  result = (float) ((arg1)->FocusZ);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_ViewerParamater_AngleX_set(void * jarg1, float jarg2) {
  ViewerParamater *arg1 = (ViewerParamater *) 0 ;
  float arg2 ;
  
  arg1 = (ViewerParamater *)jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->AngleX = arg2;
}


SWIGEXPORT float SWIGSTDCALL CSharp_ViewerParamater_AngleX_get(void * jarg1) {
  float jresult ;
  ViewerParamater *arg1 = (ViewerParamater *) 0 ;
  float result;
  
  arg1 = (ViewerParamater *)jarg1; 
  result = (float) ((arg1)->AngleX);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_ViewerParamater_AngleY_set(void * jarg1, float jarg2) {
  ViewerParamater *arg1 = (ViewerParamater *) 0 ;
  float arg2 ;
  
  arg1 = (ViewerParamater *)jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->AngleY = arg2;
}


SWIGEXPORT float SWIGSTDCALL CSharp_ViewerParamater_AngleY_get(void * jarg1) {
  float jresult ;
  ViewerParamater *arg1 = (ViewerParamater *) 0 ;
  float result;
  
  arg1 = (ViewerParamater *)jarg1; 
  result = (float) ((arg1)->AngleY);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_ViewerParamater_Distance_set(void * jarg1, float jarg2) {
  ViewerParamater *arg1 = (ViewerParamater *) 0 ;
  float arg2 ;
  
  arg1 = (ViewerParamater *)jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->Distance = arg2;
}


SWIGEXPORT float SWIGSTDCALL CSharp_ViewerParamater_Distance_get(void * jarg1) {
  float jresult ;
  ViewerParamater *arg1 = (ViewerParamater *) 0 ;
  float result;
  
  arg1 = (ViewerParamater *)jarg1; 
  result = (float) ((arg1)->Distance);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_ViewerParamater_RendersGuide_set(void * jarg1, unsigned int jarg2) {
  ViewerParamater *arg1 = (ViewerParamater *) 0 ;
  bool arg2 ;
  
  arg1 = (ViewerParamater *)jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->RendersGuide = arg2;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_ViewerParamater_RendersGuide_get(void * jarg1) {
  unsigned int jresult ;
  ViewerParamater *arg1 = (ViewerParamater *) 0 ;
  bool result;
  
  arg1 = (ViewerParamater *)jarg1; 
  result = (bool) ((arg1)->RendersGuide);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_ViewerParamater() {
  void * jresult ;
  ViewerParamater *result = 0 ;
  
  result = (ViewerParamater *)new ViewerParamater();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_ViewerParamater(void * jarg1) {
  ViewerParamater *arg1 = (ViewerParamater *) 0 ;
  
  arg1 = (ViewerParamater *)jarg1; 
  delete arg1;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_Native() {
  void * jresult ;
  Native *result = 0 ;
  
  result = (Native *)new Native();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_Native(void * jarg1) {
  Native *arg1 = (Native *) 0 ;
  
  arg1 = (Native *)jarg1; 
  delete arg1;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_Native_CreateWindow_Effekseer(void * jarg1, void * jarg2, int jarg3, int jarg4) {
  unsigned int jresult ;
  Native *arg1 = (Native *) 0 ;
  void *arg2 = (void *) 0 ;
  int arg3 ;
  int arg4 ;
  bool result;
  
  arg1 = (Native *)jarg1; 
  {
    arg2 = jarg2; 
  }
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  result = (bool)(arg1)->CreateWindow_Effekseer(arg2,arg3,arg4);
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_Native_UpdateWindow(void * jarg1) {
  unsigned int jresult ;
  Native *arg1 = (Native *) 0 ;
  bool result;
  
  arg1 = (Native *)jarg1; 
  result = (bool)(arg1)->UpdateWindow();
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_Native_ResizeWindow(void * jarg1, int jarg2, int jarg3) {
  unsigned int jresult ;
  Native *arg1 = (Native *) 0 ;
  int arg2 ;
  int arg3 ;
  bool result;
  
  arg1 = (Native *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  result = (bool)(arg1)->ResizeWindow(arg2,arg3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_Native_DestroyWindow(void * jarg1) {
  unsigned int jresult ;
  Native *arg1 = (Native *) 0 ;
  bool result;
  
  arg1 = (Native *)jarg1; 
  result = (bool)(arg1)->DestroyWindow();
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_Native_LoadEffect(void * jarg1, void * jarg2, int jarg3, wchar_t * jarg4) {
  unsigned int jresult ;
  Native *arg1 = (Native *) 0 ;
  void *arg2 = (void *) 0 ;
  int arg3 ;
  wchar_t *arg4 = (wchar_t *) 0 ;
  bool result;
  
  arg1 = (Native *)jarg1; 
  {
    arg2 = jarg2; 
  }
  arg3 = (int)jarg3; 
  arg4 = (wchar_t *)jarg4; 
  result = (bool)(arg1)->LoadEffect(arg2,arg3,(wchar_t const *)arg4);
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_Native_RemoveEffect(void * jarg1) {
  unsigned int jresult ;
  Native *arg1 = (Native *) 0 ;
  bool result;
  
  arg1 = (Native *)jarg1; 
  result = (bool)(arg1)->RemoveEffect();
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_Native_PlayEffect(void * jarg1) {
  unsigned int jresult ;
  Native *arg1 = (Native *) 0 ;
  bool result;
  
  arg1 = (Native *)jarg1; 
  result = (bool)(arg1)->PlayEffect();
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_Native_StopEffect(void * jarg1) {
  unsigned int jresult ;
  Native *arg1 = (Native *) 0 ;
  bool result;
  
  arg1 = (Native *)jarg1; 
  result = (bool)(arg1)->StopEffect();
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_Native_StepEffect(void * jarg1, int jarg2) {
  unsigned int jresult ;
  Native *arg1 = (Native *) 0 ;
  int arg2 ;
  bool result;
  
  arg1 = (Native *)jarg1; 
  arg2 = (int)jarg2; 
  result = (bool)(arg1)->StepEffect(arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_Native_Rotate(void * jarg1, float jarg2, float jarg3) {
  unsigned int jresult ;
  Native *arg1 = (Native *) 0 ;
  float arg2 ;
  float arg3 ;
  bool result;
  
  arg1 = (Native *)jarg1; 
  arg2 = (float)jarg2; 
  arg3 = (float)jarg3; 
  result = (bool)(arg1)->Rotate(arg2,arg3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_Native_Slide(void * jarg1, float jarg2, float jarg3) {
  unsigned int jresult ;
  Native *arg1 = (Native *) 0 ;
  float arg2 ;
  float arg3 ;
  bool result;
  
  arg1 = (Native *)jarg1; 
  arg2 = (float)jarg2; 
  arg3 = (float)jarg3; 
  result = (bool)(arg1)->Slide(arg2,arg3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_Native_Zoom(void * jarg1, float jarg2) {
  unsigned int jresult ;
  Native *arg1 = (Native *) 0 ;
  float arg2 ;
  bool result;
  
  arg1 = (Native *)jarg1; 
  arg2 = (float)jarg2; 
  result = (bool)(arg1)->Zoom(arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_Native_SetRandomSeed(void * jarg1, int jarg2) {
  unsigned int jresult ;
  Native *arg1 = (Native *) 0 ;
  int arg2 ;
  bool result;
  
  arg1 = (Native *)jarg1; 
  arg2 = (int)jarg2; 
  result = (bool)(arg1)->SetRandomSeed(arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_Native_Record(void * jarg1, wchar_t * jarg2, int jarg3, int jarg4, int jarg5, int jarg6, unsigned int jarg7) {
  unsigned int jresult ;
  Native *arg1 = (Native *) 0 ;
  wchar_t *arg2 = (wchar_t *) 0 ;
  int32_t arg3 ;
  int32_t arg4 ;
  int32_t arg5 ;
  int32_t arg6 ;
  bool arg7 ;
  bool result;
  
  arg1 = (Native *)jarg1; 
  arg2 = (wchar_t *)jarg2; 
  arg3 = (int32_t)jarg3; 
  arg4 = (int32_t)jarg4; 
  arg5 = (int32_t)jarg5; 
  arg6 = (int32_t)jarg6; 
  arg7 = jarg7 ? true : false; 
  result = (bool)(arg1)->Record((wchar_t const *)arg2,arg3,arg4,arg5,arg6,arg7);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Native_GetViewerParamater(void * jarg1) {
  void * jresult ;
  Native *arg1 = (Native *) 0 ;
  ViewerParamater result;
  
  arg1 = (Native *)jarg1; 
  result = (arg1)->GetViewerParamater();
  jresult = new ViewerParamater((const ViewerParamater &)result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Native_SetViewerParamater(void * jarg1, void * jarg2) {
  Native *arg1 = (Native *) 0 ;
  ViewerParamater *arg2 = 0 ;
  
  arg1 = (Native *)jarg1; 
  arg2 = (ViewerParamater *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "ViewerParamater & type is null", 0);
    return ;
  } 
  (arg1)->SetViewerParamater(*arg2);
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_Native_SetSoundMute(void * jarg1, unsigned int jarg2) {
  unsigned int jresult ;
  Native *arg1 = (Native *) 0 ;
  bool arg2 ;
  bool result;
  
  arg1 = (Native *)jarg1; 
  arg2 = jarg2 ? true : false; 
  result = (bool)(arg1)->SetSoundMute(arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_Native_SetSoundVolume(void * jarg1, float jarg2) {
  unsigned int jresult ;
  Native *arg1 = (Native *) 0 ;
  float arg2 ;
  bool result;
  
  arg1 = (Native *)jarg1; 
  arg2 = (float)jarg2; 
  result = (bool)(arg1)->SetSoundVolume(arg2);
  jresult = result; 
  return jresult;
}


#ifdef __cplusplus
}
#endif

